title: José Luis<br><br>García Nava # your name (or website title) here
logo: "/images/20230119_094157_circle.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI/ML & Cloud Consultant, PhD 
  <br><br>
  IT Consultant, Researcher, and Developer with over 30 years of experience in industrial, academic, and creative processes based on
  advanced computing systems. Currently focused on AI applications,ML engineering, and cloud computing. 
  <br><br>
  <a href="https://www.linkedin.com/in/garcianava/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
